wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.8
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1742631144
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      3:
      - 13
      - 23
      4: 3.9.19
      5: 0.17.8
      6: 4.41.2
      8:
      - 2
      - 5
      13: linux-x86_64
