# 20k data: all
CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=0 python main_real_accumulate_fuse.py --syn_data_path data_accumulate/ --gold_data_path data/worksheet/std/ --llms llama-3-8b-chinese-chat chatglm3-6b-base --task_name worksheet --num_use_samples_inner 10000 10000 --num_use_samples_init 2000 2000 --num_use_samples_outer 10 --epoch_converge 1 --outer_lr 2.5e-1 --inner_lr 5e-5 --seed 12345 --backward_batch_size 4 --outer_obj combined --inner_obj ce --init_label 10 --theta_upper_lim 1 --check_ft_every 1 --epoch_converge_fully_train 10 --threshold 0.9 --optim Adam --max_outer_iter 30 --hard --init_theta 1 --subset_outer --use_sigmoid --disable_outer_scheduler --shuffle_train --gpu 0 --small_model_name ernie-3.0-base-zh --train_batch_size 16 --fuse_dataset_weight Adjust --weight_adjust_criterial errorOnlyWrongOnlySelf --fuse_dataset_sample_selection increasedTheta --kd_slm 1 --fuse_dataset 1 --kd_aggregate_weight Entropy --BETA 0.0 --steps 4 --gen_few_shot_k 8 --gen_few_shot_pool_size 10 --gen_few_shot_ambiguous_ratio 0.5 --gen_min_length 10 --gen_max_length 200 --gen_batch_size 2

# 2k data: small version for quicker test
CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=1 python main_real_accumulate_fuse.py --syn_data_path data_accumulate/ --gold_data_path data/worksheet/std/ --llms llama-3-8b-chinese-chat chatglm3-6b-base --task_name worksheet --gold_data_num 2000 --num_use_samples_inner 2000 2000 --num_use_samples_init 400 400 --num_use_samples_outer 10 --epoch_converge 1 --outer_lr 2.5e-1 --inner_lr 5e-5 --seed 12345 --backward_batch_size 4 --outer_obj combined --inner_obj ce --init_label 10 --theta_upper_lim 1 --check_ft_every 1 --epoch_converge_fully_train 10 --threshold 0.9 --optim Adam --max_outer_iter 30 --hard --init_theta 1 --subset_outer --use_sigmoid --disable_outer_scheduler --shuffle_train --gpu 0 --small_model_name ernie-3.0-base-zh --train_batch_size 16 --fuse_dataset_weight Adjust --weight_adjust_criterial errorOnlyWrongOnlySelf --fuse_dataset_sample_selection increasedTheta --kd_slm 1 --fuse_dataset 1 --kd_aggregate_weight Entropy --BETA 0.0 --steps 4 --gen_few_shot_k 8 --gen_few_shot_pool_size 10 --gen_few_shot_ambiguous_ratio 0.5 --gen_min_length 10 --gen_max_length 200 --gen_batch_size 2

# # debug test, 100 data
# CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=0 python main_real_accumulate_fuse.py --syn_data_path data_accumulate/ --gold_data_path data/worksheet/std/ --llms llama-3-8b-chinese-chat --task_name worksheet --num_use_samples_inner 100 --num_use_samples_init 20 --num_use_samples_outer 10 --epoch_converge 1 --outer_lr 2.5e-1 --inner_lr 5e-5 --seed 12345 --backward_batch_size 4 --outer_obj combined --inner_obj ce --init_label 10 --theta_upper_lim 1 --check_ft_every 1 --epoch_converge_fully_train 1 --threshold 0.9 --optim Adam --max_outer_iter 30 --hard --init_theta 1 --subset_outer --use_sigmoid --disable_outer_scheduler --shuffle_train --gpu 0 --small_model_name ernie-3.0-base-zh --train_batch_size 16 --fuse_dataset_weight Adjust --weight_adjust_criterial errorOnlyWrongOnlySelf --fuse_dataset_sample_selection increasedTheta --kd_slm 1 --fuse_dataset 1 --kd_aggregate_weight Entropy --BETA 0.0 --steps 4 --gen_few_shot_k 8 --gen_few_shot_pool_size 10 --gen_few_shot_ambiguous_ratio 0.5 --gen_min_length 10 --gen_max_length 200 --gen_batch_size 1


CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=0 python main_real_accumulate_fuse.py --syn_data_path data_accumulate/ --gold_data_path data/worksheet/std/ --llms llama-3-8b-chinese-chat chatglm3-6b-base --task_name worksheet --gold_data_num 2000 --num_use_samples_inner 4000 4000 --num_use_samples_init 800 800 --num_use_samples_outer 10 --epoch_converge 1 --outer_lr 2.5e-1 --inner_lr 5e-5 --seed 12345 --backward_batch_size 4 --outer_obj combined --inner_obj ce --init_label 10 --theta_upper_lim 1 --check_ft_every 1 --epoch_converge_fully_train 10 --threshold 0.9 --optim Adam --max_outer_iter 30 --hard --init_theta 1 --subset_outer --use_sigmoid --disable_outer_scheduler --shuffle_train --gpu 0 --small_model_name ernie-3.0-base-zh --train_batch_size 16 --fuse_dataset_weight Adjust --weight_adjust_criterial errorOnlyWrongOnlySelf --fuse_dataset_sample_selection increasedTheta --kd_slm 1 --fuse_dataset 1 --kd_aggregate_weight Entropy --BETA 0.0 --steps 4 --gen_few_shot_k 8 --gen_few_shot_pool_size 10 --gen_few_shot_ambiguous_ratio 0.5 --gen_min_length 10 --gen_max_length 200 --gen_batch_size 2
CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=0 python main_real_accumulate_fuse.py --syn_data_path data_accumulate/ --gold_data_path data/worksheet/std/ --llms llama-3-8b-chinese-chat --task_name worksheet --gold_data_num 2000 --num_use_samples_inner 8000 --num_use_samples_init 1600 --num_use_samples_outer 10 --epoch_converge 1 --outer_lr 2.5e-1 --inner_lr 5e-5 --seed 12345 --backward_batch_size 4 --outer_obj combined --inner_obj ce --init_label 10 --theta_upper_lim 1 --check_ft_every 1 --epoch_converge_fully_train 10 --threshold 0.9 --optim Adam --max_outer_iter 30 --hard --init_theta 1 --subset_outer --use_sigmoid --disable_outer_scheduler --shuffle_train --gpu 0 --small_model_name ernie-3.0-base-zh --train_batch_size 16 --fuse_dataset_weight Adjust --weight_adjust_criterial errorOnlyWrongOnlySelf --fuse_dataset_sample_selection increasedTheta --kd_slm 1 --fuse_dataset 1 --kd_aggregate_weight Entropy --BETA 0.0 --steps 4 --gen_few_shot_k 8 --gen_few_shot_pool_size 10 --gen_few_shot_ambiguous_ratio 0.5 --gen_min_length 10 --gen_max_length 200 --gen_batch_size 2
CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=0 python main_real_accumulate_fuse.py --syn_data_path data_accumulate/ --gold_data_path data/worksheet/std/ --llms chatglm3-6b-base --task_name worksheet --gold_data_num 2000 --num_use_samples_inner 8000 --num_use_samples_init 1600 --num_use_samples_outer 10 --epoch_converge 1 --outer_lr 2.5e-1 --inner_lr 5e-5 --seed 12345 --backward_batch_size 4 --outer_obj combined --inner_obj ce --init_label 10 --theta_upper_lim 1 --check_ft_every 1 --epoch_converge_fully_train 10 --threshold 0.9 --optim Adam --max_outer_iter 30 --hard --init_theta 1 --subset_outer --use_sigmoid --disable_outer_scheduler --shuffle_train --gpu 0 --small_model_name ernie-3.0-base-zh --train_batch_size 16 --fuse_dataset_weight Adjust --weight_adjust_criterial errorOnlyWrongOnlySelf --fuse_dataset_sample_selection increasedTheta --kd_slm 1 --fuse_dataset 1 --kd_aggregate_weight Entropy --BETA 0.0 --steps 4 --gen_few_shot_k 8 --gen_few_shot_pool_size 10 --gen_few_shot_ambiguous_ratio 0.5 --gen_min_length 10 --gen_max_length 200 --gen_batch_size 2
