# # python main_loss_cross_validation_fuse_with_test_single_dynamic.py --gold_data_path data/imdb/std/ --llms gpt2-xl llama-2-7b-chat-hf vicuna-7b-1.5v opt-6.7b chatglm3-6b-base flan-t5-xl --task_name imdb --num_use_samples_inner 10000 10000 10000 10000 10000 10000 --num_use_samples_outer 50 --epoch_converge 1 --outer_lr 2.5e-1 --inner_lr 2e-5 --seed 12345 --backward_batch_size 4096 --outer_obj combined --inner_obj ce --init_label 10 --theta_upper_lim 1 --check_ft_every 1 --epoch_converge_fully_train 3 --threshold 0.9 --optim Adam --max_outer_iter 30 --hard --init_theta 1 --subset_outer --use_sigmoid --disable_outer_scheduler --shuffle_train --gpu 2 --small_model_name bert-base-uncased --train_batch_size 16 --fuse_dataset_weight Adjust --weight_adjust_criterial errorOnlyWrongOnlySelfTestAll --fuse_dataset_sample_selection increasedTheta --kd_slm 0 --fuse_dataset 0 --kd_aggregate_weight Entropy --BETA 0.0
# python main_loss_cross_validation_fuse_with_test_single_dynamic.py --gold_data_path data/imdb/std/ --llms gpt2-xl llama-2-7b-chat-hf vicuna-7b-1.5v opt-6.7b chatglm3-6b-base flan-t5-xl --task_name imdb --num_use_samples_inner 1000 1000 1000 1000 1000 1000 --num_use_samples_outer 50 --epoch_converge 1 --outer_lr 2.5e-1 --inner_lr 2e-5 --seed 12345 --backward_batch_size 4096 --outer_obj combined --inner_obj ce --init_label 10 --theta_upper_lim 1 --check_ft_every 1 --epoch_converge_fully_train 3 --threshold 0.9 --optim Adam --max_outer_iter 30 --hard --init_theta 1 --subset_outer --use_sigmoid --disable_outer_scheduler --shuffle_train --gpu 2 --small_model_name bert-base-uncased --train_batch_size 16 --fuse_dataset_weight Adjust --weight_adjust_criterial errorOnlyWrongOnlySelfTestAll --fuse_dataset_sample_selection increasedTheta --kd_slm 0 --fuse_dataset 0 --kd_aggregate_weight Entropy --BETA 0.0
# python main_loss_cross_validation_fuse_with_test_single_dynamic.py --gold_data_path data/imdb/std/ --llms gpt2-xl llama-2-7b-chat-hf vicuna-7b-1.5v opt-6.7b chatglm3-6b-base flan-t5-xl --task_name imdb --num_use_samples_inner 1000 1000 1000 1000 1000 1000 --num_use_samples_outer 50 --epoch_converge 1 --outer_lr 2.5e-1 --inner_lr 2e-5 --seed 12345 --backward_batch_size 4096 --outer_obj combined --inner_obj ce --init_label 10 --theta_upper_lim 1 --check_ft_every 1 --epoch_converge_fully_train 6 --threshold 0.9 --optim Adam --max_outer_iter 30 --hard --init_theta 1 --subset_outer --use_sigmoid --disable_outer_scheduler --shuffle_train --gpu 2 --small_model_name bert-base-uncased --train_batch_size 16 --fuse_dataset_weight Adjust --weight_adjust_criterial errorOnlyWrongOnlySelfTestAll --fuse_dataset_sample_selection increasedTheta --kd_slm 0 --fuse_dataset 0 --kd_aggregate_weight Entropy --BETA 0.0



#!/bin/bash
 
# strings=(
# #   "data_new/"
# #   "data_accumulate/imdb/single_copied/bert-base-uncased/increasedTheta_KD1_FuseDataset1/fewshotK8_5_0.5/1/"
#   "data_accumulate/imdb/gpt2-xl_1000__llama-2-7b-chat-hf_1000__vicuna-7b-1.5v_1000__opt-6.7b_1000__flan-t5-xl_1000__chatglm3-6b-base_1000/bert-base-uncased/increasedTheta_KD1_FuseDataset1/fewshotK8_5_0.5/12345/"
# )
# for syn_data_path in "${strings[@]}"; do
#     python main_loss_cross_validation_fuse_with_test_single_dynamic.py --syn_data_path $syn_data_path --gold_data_path data/imdb/std/ --llms gpt2-xl llama-2-7b-chat-hf vicuna-7b-1.5v opt-6.7b chatglm3-6b-base flan-t5-xl --task_name imdb --num_use_samples_inner 1000 1000 1000 1000 1000 1000 --num_use_samples_outer 50 --epoch_converge 1 --outer_lr 2.5e-1 --inner_lr 2e-5 --seed 12345 --backward_batch_size 4096 --outer_obj combined --inner_obj ce --init_label 10 --theta_upper_lim 1 --check_ft_every 1 --epoch_converge_fully_train 3 --threshold 0.9 --optim Adam --max_outer_iter 30 --hard --init_theta 1 --subset_outer --use_sigmoid --disable_outer_scheduler --shuffle_train --gpu 2 --small_model_name bert-base-uncased --train_batch_size 16 --fuse_dataset_weight Adjust --weight_adjust_criterial errorOnlyWrongOnlySelfTestAll --fuse_dataset_sample_selection increasedTheta --kd_slm 0 --fuse_dataset 0 --kd_aggregate_weight Entropy --BETA 0.0
#     python main_loss_cross_validation_fuse_with_test_single_dynamic.py --syn_data_path $syn_data_path --gold_data_path data/imdb/std/ --llms gpt2-xl llama-2-7b-chat-hf vicuna-7b-1.5v opt-6.7b chatglm3-6b-base flan-t5-xl --task_name imdb --num_use_samples_inner 1000 1000 1000 1000 1000 1000 --num_use_samples_outer 50 --epoch_converge 1 --outer_lr 2.5e-1 --inner_lr 2e-5 --seed 12345 --backward_batch_size 4096 --outer_obj combined --inner_obj ce --init_label 10 --theta_upper_lim 1 --check_ft_every 1 --epoch_converge_fully_train 6 --threshold 0.9 --optim Adam --max_outer_iter 30 --hard --init_theta 1 --subset_outer --use_sigmoid --disable_outer_scheduler --shuffle_train --gpu 2 --small_model_name bert-base-uncased --train_batch_size 16 --fuse_dataset_weight Adjust --weight_adjust_criterial errorOnlyWrongOnlySelfTestAll --fuse_dataset_sample_selection increasedTheta --kd_slm 0 --fuse_dataset 0 --kd_aggregate_weight Entropy --BETA 0.0
# done

# strings=(
# #   "data_new/"
#   "data_accumulate/imdb/single_copied/bert-base-uncased/increasedTheta_KD1_FuseDataset1/fewshotK8_5_0.5/1/"
# #   "data_accumulate/imdb/gpt2-xl_1000__llama-2-7b-chat-hf_1000__vicuna-7b-1.5v_1000__opt-6.7b_1000__flan-t5-xl_1000__chatglm3-6b-base_1000/bert-base-uncased/increasedTheta_KD1_FuseDataset1/fewshotK8_5_0.5/12345/"
# )
# for syn_data_path in "${strings[@]}"; do
#     # python main_loss_cross_validation_fuse_with_test_single_dynamic.py --syn_data_path $syn_data_path --gold_data_path data/imdb/std/ --llms gpt2-xl llama-2-7b-chat-hf vicuna-7b-1.5v opt-6.7b chatglm3-6b-base flan-t5-xl --task_name imdb --num_use_samples_inner 1000 1000 1000 1000 1000 1000 --num_use_samples_outer 50 --epoch_converge 1 --outer_lr 2.5e-1 --inner_lr 2e-5 --seed 12345 --backward_batch_size 4096 --outer_obj combined --inner_obj ce --init_label 10 --theta_upper_lim 1 --check_ft_every 1 --epoch_converge_fully_train 3 --threshold 0.9 --optim Adam --max_outer_iter 30 --hard --init_theta 1 --subset_outer --use_sigmoid --disable_outer_scheduler --shuffle_train --gpu 2 --small_model_name bert-base-uncased --train_batch_size 16 --fuse_dataset_weight Adjust --weight_adjust_criterial errorOnlyWrongOnlySelfTestAll --fuse_dataset_sample_selection increasedTheta --kd_slm 0 --fuse_dataset 0 --kd_aggregate_weight Entropy --BETA 0.0
#     python main_loss_cross_validation_fuse_with_test_single_dynamic.py --syn_data_path $syn_data_path --gold_data_path data/imdb/std/ --llms gpt2-xl llama-2-7b-chat-hf vicuna-7b-1.5v opt-6.7b chatglm3-6b-base flan-t5-xl --task_name imdb --num_use_samples_inner 1000 1000 1000 1000 1000 1000 --num_use_samples_outer 50 --epoch_converge 1 --outer_lr 2.5e-1 --inner_lr 2e-5 --seed 12345 --backward_batch_size 4096 --outer_obj combined --inner_obj ce --init_label 10 --theta_upper_lim 1 --check_ft_every 1 --epoch_converge_fully_train 6 --threshold 0.9 --optim Adam --max_outer_iter 30 --hard --init_theta 1 --subset_outer --use_sigmoid --disable_outer_scheduler --shuffle_train --gpu 2 --small_model_name bert-base-uncased --train_batch_size 16 --fuse_dataset_weight Adjust --weight_adjust_criterial errorOnlyWrongOnlySelfTestAll --fuse_dataset_sample_selection increasedTheta --kd_slm 0 --fuse_dataset 0 --kd_aggregate_weight Entropy --BETA 0.0
# done


strings=(
  "data_new/"
  "data_accumulate/imdb/single_copied/bert-base-uncased/increasedTheta_KD1_FuseDataset1/fewshotK8_5_0.5/12345/"
  "data_accumulate/imdb/gpt-3.5-turbo-instruct_1000__gpt-4-turbo-preview_1000/bert-base-uncased/increasedTheta_KD1_FuseDataset1/fewshotK8_5_0.5/12345/"
)
for syn_data_path in "${strings[@]}"; do
    python main_loss_cross_validation_fuse_with_test_single_dynamic.py --syn_data_path $syn_data_path --gold_data_path data/imdb/std/ --llms gpt-3.5-turbo-instruct gpt-4-turbo-preview --task_name imdb --num_use_samples_inner 1000 1000 --num_use_samples_outer 50 --epoch_converge 1 --outer_lr 2.5e-1 --inner_lr 2e-5 --seed 12345 --backward_batch_size 4096 --outer_obj combined --inner_obj ce --init_label 10 --theta_upper_lim 1 --check_ft_every 1 --epoch_converge_fully_train 6 --threshold 0.9 --optim Adam --max_outer_iter 30 --hard --init_theta 1 --subset_outer --use_sigmoid --disable_outer_scheduler --shuffle_train --gpu 2 --small_model_name bert-base-uncased --train_batch_size 16 --fuse_dataset_weight Adjust --weight_adjust_criterial errorOnlyWrongOnlySelfTestAll --fuse_dataset_sample_selection increasedTheta --kd_slm 0 --fuse_dataset 0 --kd_aggregate_weight Entropy --BETA 0.0
done

# strings=(
#   "data_accumulate/qnli/single_copied/bert-base-uncased/increasedTheta_KD1_FuseDataset1/fewshotK4_5_0.5/42/"
#   # "data_accumulate/qnli/gpt2-xl_1000__llama-2-7b-chat-hf_1000__vicuna-7b-1.5v_1000__opt-6.7b_1000__flan-t5-xl_1000__chatglm3-6b-base_1000/bert-base-uncased/increasedTheta_KD1_FuseDataset1/fewshotK4_5_0.5/12345/"
#   "data_new/"
# )
# for syn_data_path in "${strings[@]}"; do
#     # python main_loss_cross_validation_fuse_with_test_single_dynamic.py --syn_data_path $syn_data_path --gold_data_path data/qnli/std/ --llms gpt2-xl llama-2-7b-chat-hf vicuna-7b-1.5v opt-6.7b chatglm3-6b-base flan-t5-xl --task_name qnli --num_use_samples_inner 1000 1000 1000 1000 1000 1000 --num_use_samples_outer 50 --epoch_converge 1 --outer_lr 2.5e-1 --inner_lr 2e-5 --seed 12345 --backward_batch_size 4096 --outer_obj combined --inner_obj ce --init_label 10 --theta_upper_lim 1 --check_ft_every 1 --epoch_converge_fully_train 3 --threshold 0.9 --optim Adam --max_outer_iter 30 --hard --init_theta 1 --subset_outer --use_sigmoid --disable_outer_scheduler --shuffle_train --gpu 1 --small_model_name bert-base-uncased --train_batch_size 16 --fuse_dataset_weight Adjust --weight_adjust_criterial errorOnlyWrongOnlySelfTestAll --fuse_dataset_sample_selection increasedTheta --kd_slm 0 --fuse_dataset 0 --kd_aggregate_weight Entropy --BETA 0.0
#     python main_loss_cross_validation_fuse_with_test_single_dynamic.py --syn_data_path $syn_data_path --gold_data_path data/qnli/std/ --llms gpt2-xl llama-2-7b-chat-hf vicuna-7b-1.5v opt-6.7b chatglm3-6b-base flan-t5-xl --task_name qnli --num_use_samples_inner 1000 1000 1000 1000 1000 1000 --num_use_samples_outer 50 --epoch_converge 1 --outer_lr 2.5e-1 --inner_lr 2e-5 --seed 12345 --backward_batch_size 4096 --outer_obj combined --inner_obj ce --init_label 10 --theta_upper_lim 1 --check_ft_every 1 --epoch_converge_fully_train 6 --threshold 0.9 --optim Adam --max_outer_iter 30 --hard --init_theta 1 --subset_outer --use_sigmoid --disable_outer_scheduler --shuffle_train --gpu 1 --small_model_name bert-base-uncased --train_batch_size 16 --fuse_dataset_weight Adjust --weight_adjust_criterial errorOnlyWrongOnlySelfTestAll --fuse_dataset_sample_selection increasedTheta --kd_slm 0 --fuse_dataset 0 --kd_aggregate_weight Entropy --BETA 0.0
# done